name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2 

    - name: Add .nojekyll file
      run: touch ./.nojekyll
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
